### ISSUE TITLE
iPhone 6 Displaying Desktop Version

### ISSUE THREAD

**Issue by fjcaetano** [mitmproxy/mitmproxy.org#2]
I tried to install the certificates for iOS using the [documentation here](http://mitmproxy.org/doc/certinstall/webapp.html) however, when accessing mitm.it from my iPhone 6, I get the desktop version of the site.

I haven't tried any browsers other than Safari nor a different mobile device model, but it also happened on a different iPhone 6.

**Comment by mhils** [comment]
This should be fixed now.

**Comment by fjcaetano** [comment]
Actually, it's all broken now, even on desktop

**Comment by mhils** [comment]
I get the "If you can see this, traffic is not passing through mitmproxy." warning without proxy and the web app with proxy - works perfectly fine for me.

Cheers,
Max
