### ISSUE TITLE
Update Copyright 2015 --> 2018

### ISSUE THREAD

**Issue by jmoujaes** [mitmproxy/mitmproxy.org#22]
Hello. While getting to know the project today I realized that the copyright footer is still 2015.
https://github.com/mitmproxy/mitmproxy.org/blob/2138d3aaf6f47744cd2fc2362a8ee137ad43555c/src/_layout.html#L45

I'd be happy to make a PR to update it to 2018, or add a couple lines of javascript to make it dynamic.

**Comment by mhils** [comment]
Thanks for letting us know! We've been slacking - a new website is in the works, with a year-less footer: https://github.com/mitmproxy/www/blob/master/src/themes/mitmproxy/layouts/partials/footer.html 😁

**Comment by jmoujaes** [comment]
Haha gotcha. Do you think it's worth updating then or just waiting for the new site?

**Comment by mhils** [comment]
I have updated to footer on the current website _just for you_ (still needs to get through caches), but generally we're dealing with sunk costs here. 😉 Thank you for the report though, always appreciated.

**Comment by jmoujaes** [comment]
Sounds good, cheers!
