### ISSUE TITLE
Image too large

### ISSUE THREAD

**Issue by emersion** [mitmproxy/mitmproxy.org#8]
In http://mitmproxy.org/doc/certinstall.html

![capture d ecran 2015-08-21 a 14 22 24](https://cloud.githubusercontent.com/assets/506932/9408138/1188f9f0-4810-11e5-82c6-95c9ca848d00.png)

**Comment by mhils** [comment]
Thanks. This is already fixed by https://github.com/mitmproxy/mitmproxy/commit/7990503eaf738e655b50f8fb55d6eff9bd11bdec, we just need to update the docs on the site.
