### ISSUE TITLE
Replace Slack URL

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy.org#9]
On the main page, there's a link to `https://mitmproxy-slack.herokuapp.com/`, which should be replaced by `slack.mitmproxy.org`. The latest changes to index.html are not pushed, so I cannot update that.

**Comment by dweinstein** [comment]
actually the URL is https://mitmproxy.slack.com

**Comment by mhils** [comment]
http://slack.mitmproxy.org/ was hosting https://github.com/rauchg/slackin - apparently it went down under, I'll take a look. http://mitmproxy-slack.herokuapp.com/ works as a fallback.

**Comment by dweinstein** [comment]
oh, whoops sorry.
